# Generated by Django 4.1.3 on 2022-12-09 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_newsstory_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsstory',
            options={'ordering': ['-pub_date'], 'verbose_name': 'NewsStory', 'verbose_name_plural': 'NewsStory'},
        ),
    ]
