# Generated by Django 4.1.3 on 2022-12-18 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_category_newsstory_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsstory',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
