# Generated by Django 4.1.3 on 2022-12-18 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_category_alter_newsstory_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsstory',
            old_name='favourited_by',
            new_name='postLiked',
        ),
    ]
