# Generated by Django 4.1.3 on 2022-12-18 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_rename_favourited_by_newsstory_postliked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsstory',
            old_name='postLiked',
            new_name='favourited_by',
        ),
    ]
